---
version: '3.5'
services:
  wetty-sshd:
    image: quay.io/cdis/awshelper:master
    network_mode: service:nginx
    container_name: 'wetty-sshd'
    environment:
        - HOSTNAME=reuben.planx-pla.net
        - NAMESPACE=reuben
    volumes:
      - ${DATA_VOLUME}:/data
      - ${USER_VOLUME}:/home/ubuntu/pd
    entrypoint: [ "/bin/bash" ]
    command:
      - "-c"
        # move cloud-automation out of the way for hatchery apps
      - "(cd /home/ubuntu && mv cloud-automation .cloud-automation && echo \"export NAMESPACE=$NAMESPACE\" >> .bashrc); exec /bin/bash /opt/usersshd/sshdStart.sh"
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -q 1 localhost 2222 < /dev/null"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  wetty:
    #image: wetty:reuben
    image: quay.io/cdis/ws-wetty:2021.01
    network_mode: service:nginx
    container_name: wetty
    tty: true
    environment:
      - SSHHOST=localhost
      - SSHPASS=gen3
      - SSHUSER=ubuntu
      - SSHPORT=2222
      - BASE=/lw-workspace/proxy/wetty/
      - TITLE=Gen3Terminal
  nginx:
    # testing against a local build of the Dockerfile
    image: "quay.io/cdis/ws-nginx-proxy:2021.01"
    ports: 
      - "${SERVICE_PORT}:7780"
    environment:
      - "APP_PORT=3000"
      - "APP_PREFIX=lw-workspace/proxy/wetty"
      - "IN_PREFIX=lw-workspace/proxy/wetty"
      - "REDIRECT_PREFIX=https://reuben.planx-pla.net"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7780/_proxy_status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
